---
title: Siteleaf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Бояринцев .NET
description: Веб-разработка на .NET
avatar: https://raw.githubusercontent.com/boyarincev/boyarincev.github.io/master/images/ej.jpg
author:
  name: Бояринцев Стас
  email: boyarincev@gmail.com
footer-links:
  dribbble: 
  email: boyarincev@gmail.com
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: boyarincev
  pinterest: 
  rss: rss
  twitter: boyarincev
  stackoverflow: 
  youtube: 
  googleplus: 
excerpt_separator: "<!--excerpt-->"
disqus: boyarincev
google_analytics: UA-64833951-2
yandex_analytics: 33636539
url: http://boyarincev.net
baseurl: ''
permalink: "/:year/:month/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :compressed
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
markdown: kramdown
highlighter: rouge
incremental: false
liquid:
  error_mode: warn
